apiVersion: apps/v1
kind: Deployment
metadata:
  name: terra-controller-webhook
  labels:
    app: terrascan-admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terrascan-admission-webhook
  template:
    metadata:
      labels:
        app: terrascan-admission-webhook
    spec:
      containers:
      - name: terrascan-1-5
        image: patilpankaj212/terrascan:sshkeys
        resources:
          limits:
            memory: "256Mi"
            cpu: "1"
        ports:
          - containerPort: 443
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
        env:
          - name: K8S_WEBHOOK_API_KEY
            value: yoursecretapikey
        volumeMounts:
          - mountPath: /data
            name: certspath
          - mountPath: /etc/github-secret
            name: ssh-keys-github
            readOnly: true
          - mountPath: /etc/ssh-config-secret
            name: ssh-config
            readOnly: true
          - mountPath: /etc/ssh-known-hosts-secret
            name: ssh-known-hosts
            readOnly: true
        command: ["/bin/sh", "-c"]
        args:
          - >
            cp /etc/github-secret/ssh-private-key /home/terrascan/.ssh/id_ed25519_github &&
            cp /etc/ssh-config-secret/ssh-config /home/terrascan/.ssh/config &&
            cp /etc/ssh-known-hosts-secret/ssh-known-hosts /home/terrascan/.ssh/known_hosts &&
            chmod -R 400 /home/terrascan/.ssh/* &&
            terrascan server --cert-path /data/server.crt --key-path /data/server.key -p 443 -l debug -c /data/config.toml
      volumes:
        - name: certspath
          hostPath:
            path: path_to_repo/certs
        #add all required ssh keys need to clone your repos
        - name: ssh-keys-github
          secret:
            secretName: github-secret
        #add a secret for git config file    
        - name: ssh-config
          secret:
            secretName: ssh-config-secret
        #add a configmap for the ssh known_hosts file
        - name: ssh-known-hosts
          configMap:
            name: known-hosts-config