apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: terra-controller-service.default.svc
webhooks:
  - name: terra-controller-service.default.svc
    rules:
    - apiGroups:
      - ""
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - pods
        - services
    failurePolicy: Fail
    clientConfig:
      service:
        name: terra-controller-service
        namespace: default
        path: /v1/k8s/webhooks/yoursecretapikey/scan/validate
      #caBundle: 
    sideEffects: None
    admissionReviewVersions: ["v1"]
